AWSTemplateFormatVersion: "2010-09-09"
Description: CFN template to create EC2 to launch template resources
Resources:
  MyLaunchTemplate1:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: MyLaunchTemplate
      LaunchTemplateData:
        InstanceType: t2.micro

  WindowsInstance1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: fouronekey2
      ImageId: ami-09e13647920b2ba1d
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate1
        Version: !GetAtt MyLaunchTemplate1.LatestVersionNumber
      Tags:
        - Key: Name
          Value: WindowsInstance

  UbuntuInstance1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: fouronekey2
      ImageId: ami-0729e439b6769d6ab
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate1
        Version: !GetAtt MyLaunchTemplate1.LatestVersionNumber
      Tags:
        - Key: Name
          Value: UbuntuInstance


