AWSTemplateFormatVersion: "2010-09-09"
Description: Simple Lambda function from Cloudformation
Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloLambdaFunction
      Handler: index.handler
      Runtime: python3.9
      Role: !GetAtt LambdaFunctionRole.Arn
      Code:
        ZipFile: |
          def handler(event, context):
              # TODO implement
              return print("Hello AWS!")

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: AppendToLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
