AWSTemplateFormatVersion: "2010-09-09"
Description: CFN template to create Debian instance to launch template resources
Resources:
  ASLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      #      InstanceId: !Ref DebianInstance1
      ImageId: ami-09a41e26df464c548
      InstanceType: t2.micro
      KeyName: fouronekey2

  ASGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        - us-east-1a
      AutoScalingGroupName: asg
      LaunchConfigurationName: !Ref ASLaunchConfig
      MaxSize: 1
      MinSize: 1
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: True






