Parameters:
  BucketName:
    Type: String
    Description: Bucket name

Description: Creating an S3 bucket with minimal inputs
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
#      VersioningConfiguration:
#        Status: Enabled