Description:  Creates an EC2 instance with the output from 4.1.3 subnet and VPC

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'

  Instancetype:
    Description: Free Instance type for EC2
    Type: String
Resources:
  EC2Server:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: fouronekey2
      SubnetId: !ImportValue four-publicsubnetid
      ImageId: !Ref LatestAmiId
      InstanceType:  !Ref Instancetype
      SecurityGroupIds:
        - Ref: SecurityGroup1
      Tags:
        - Key: "Name"
          Value: "EC2PublicServer"
  SecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Description: Public Server Security Group
    Properties:
      GroupDescription: Allow ICMP and Tcp
      VpcId: !ImportValue four-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 142.188.2.24/24
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  PublicServerElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Server
      Tags:
        - Key: "Name"
          Value: "PublicServerElasticIp"

  EC2PrivateServer:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: fouronekey2
      SubnetId: !ImportValue four-privatesubnetid
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref Instancetype
      SecurityGroupIds:
        - Ref: SecurityGroupPrivate
      Tags:
        - Key: "Name"
          Value: "EC2PrivateServer"


  SecurityGroupPrivate:
    Type: AWS::EC2::SecurityGroup
    Description: Private Server Security Group
    Properties:
      GroupDescription: Allow ICMP and Tcp
      VpcId: !ImportValue four-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 0.0.0.0/0

Outputs:
  EC2ServerIDOutput:
    Description: A reference to the created EC2 INSTANCE ID
    Value: !Ref EC2Server
    Export:
      Name: Ec2ServerId
  PublicIpOutput:
    Description: Server Private IP
    Value: !GetAtt EC2Server.PrivateIp
    Export:
      Name: !Sub "${AWS::StackName}-PublicServerPrivateIp"

  EC2ServerPublicIp:
    Description: Public IP of EC2 Server
    Value: !GetAtt EC2Server.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-EC2ServerPublicIp"
  EC2PrivateServerIp:
    Description: Public IP of EC2 Server
    Value: !GetAtt EC2PrivateServer.PrivateIp
    Export:
      Name: !Sub "${AWS::StackName}-EC2PrivateServerIp"


