#AWSTemplateFormatVersion: "2010-09-09"
Description: Tempalte to create an open search service
Parameters:
  MasterInstanceType:
    Description: Please choose the type of instance you want such as m3.medium.search or something in the json parameter file
    Type: String
    AllowedValues:
      - c5.large.search
      - r5.large.search
  DataNodeInstanceType:
    Description: Data node instance type
    Type: String
    AllowedValues:
      - c5.large.search
      - r5.large.search
  WarmInstanceType:
    Description: The instance type for the cluster's warm nodes.
    Type: String
    AllowedValues:
      - ultrawarm1.medium.search
  EBSVolumeSize:
    Description: EBS Volume Size
    Type: String
  EBSVolumeType:
    Description: EBS Volume Size
    Type: String
    AllowedValues:
      - gp2
      - gp3
Resources:
  OpenSearchCluster:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: test
      AdvancedSecurityOptions:
        Enabled: True
        InternalUserDatabaseEnabled: True
        MasterUserOptions:
          MasterUserName: '{{resolve:secretsmanager:OpenSearchuser:SecretString:UserName}}'
          MasterUserPassword: '{{resolve:secretsmanager:OpenSearchuser:SecretString:Password}}'
      ClusterConfig:
        DedicatedMasterCount: 3
        DedicatedMasterEnabled: True
        DedicatedMasterType: !Ref MasterInstanceType
        InstanceCount: 3
        InstanceType: !Ref DataNodeInstanceType
        WarmEnabled: True
        WarmCount: 2
        WarmType: !Ref WarmInstanceType
      DomainEndpointOptions:
        EnforceHTTPS: True
      NodeToNodeEncryptionOptions:
        Enabled: True
      EncryptionAtRestOptions:
        Enabled: True
      EBSOptions:
        EBSEnabled: True
        VolumeSize: !Ref EBSVolumeSize
        VolumeType: !Ref EBSVolumeType
      Tags:
        - Key: Name
          Value: OpenSearchProject
Outputs:
  opensearchdomainendpoint1:
    Description: Output of the domain endpoint
    Value: !GetAtt OpenSearchCluster.DomainEndpoint
    Export:
      Name: opensearchdomainendpoint1


